### ISSUE TITLE
AssertionError: Overflowed string length is not supported yet.

### ISSUE THREAD

**Issue by longldktmm** [bongtrop/hbctool#10]
When I " hbctool asm edited index.android.bundle"
hbc.setString(string["id"], string["value"])
\appdata\local\programs\python\python39-32\lib\site-packages\hbctool\hbc\hbc59\__init__.py", line 142, in setString
    assert l <= length, "Overflowed string length is not supported yet."
AssertionError: Overflowed string length is not supported yet.
I'm using Python 3.9.6, what should I fix?

**Comment by genox997** [comment]
i have the same problem

**Comment by longldktmm** [comment]
I think because new String is longer than old String. if shotter, will
padding

Vào 17:59, T.3, 21 Th9, 2021 Claudio Genovese ***@***.***> đã
viết:

**Comment by bongtrop** [comment]
It is hard to construct new file structure if we have to put longer string in the Hermes. All afterward pointer will be changed.
