### ISSUE TITLE
Support for version 62

### ISSUE THREAD

**Issue by Karim0x1** [bongtrop/hbctool#3]
Hi, thanks for making this tool, I thought I wouldn't be able to analyze react native apps anymore !
Anyway, I don't know if I should create another issue, but could you also add support for version 62 please ?
Used by: [com.canaltp.ametis](https://play.google.com/store/apps/details?id=com.canaltp.ametis)

Thank you

**Comment by bongtrop** [comment]
I'm working on it.

**Comment by euzada** [comment]
> I'm working on it.

That a great support of the tool. If you give us some guidelines, we can also help.

Regards,

**Comment by TranDatDT** [comment]
> I'm working on it.

Hope you doing well. Is there any update on this version?
