### ISSUE TITLE
How to decode UTF16 in strings?

### ISSUE THREAD

**Issue by d1ret** [bongtrop/hbctool#33]
How to decode and change utf16 values in strings.json?

example:
`    {
        "id": 27774,
        "isUTF16": true,
        "value": "3906270645062000480627062d062f06"
    }
 `

**Comment by belext** [comment]
Here's how to do it: https://gchq.github.io/CyberChef/#recipe=From_Charcode('Space',16)&oenc=1200
And use "To Charcode" recipe to convert it back. Make sure to select UTF-16LE encoding for the resulting text.
