### ISSUE TITLE
The HBC version (76) is not supported.

### ISSUE THREAD

**Issue by Prakhar-Srivastava** [bongtrop/hbctool#8]
Add support for latest hermes

**Comment by bongtrop** [comment]
@ErbaZZ is working on it. Cooming soon !!!!

**Comment by OrkhanAlikhanov** [comment]
@bongtrop  Please publish it. [Latest version is 0.1.3](https://pypi.org/project/hbctool)

**Comment by bongtrop** [comment]
@OrkhanAlikhanov We are testing with a real app. We will release the new version and publish it soon.

**Comment by OrkhanAlikhanov** [comment]
Cool. I disassembled boltfood app. Version 1.9.0 for android. Didn't reassemble it back though, I only needed to see something there and I were able to thanks to you guys' effort. I really appreciate 👍🏽👍🏽👍🏽
